################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c \
D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_cortex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_dma.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_gpio.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim_ex.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart.o \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_cortex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_dma.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_gpio.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim_ex.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart.d \
./Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_adc_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_cortex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_dma.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_flash_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_gpio.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_i2c_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_pwr_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_rcc_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_spi_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_tim_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F0xx_HAL_Driver/stm32f0xx_hal_uart_ex.o: D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mfloat-abi=soft '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F030x6 -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/MCU" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Device/ST/STM32F0xx/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/Drivers/CMSIS/Include" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Uart" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/Timer/Timer1" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_RingBuf" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Srv/Srv_Delay" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/DIO" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/HWE/TM1637" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Buzzer" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED7" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/LED" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/Application/User/OS_Sched" -I"D:/Working/Workspace/BadmintonBoard_V2/BadmintonBoard_Main/BadmintonV2_Main/SW4STM32/BadmintonV2_Main/DeviceDriver/Button"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


